name: Build docker image

on:
  push:
    branches: [ docker ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: login to docker
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u carrotindustries --password-stdin
    - uses: actions/checkout@v2
      with:
        path: src
    - name: build docker image
      run: docker build . -f src/Dockerfile --network=host -t horizoneda/horizon:latest
    - name: publish docker image
      run: docker push horizoneda/horizon:latest
